version: 2

jobs:
  build-and-push:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - add_ssh_keys:
            fingerprints:
              - "8f:1e:89:48:d4:ed:92:4c:23:c0:f3:e3:c1:74:c5:28"
      - run:
          name: install dependencies
          command: |
            npm i
            npm run install
      - run:
          name: build gitbook
          command: npm run build
      - run:
          name: git config
          command: |
            git config --global user.email "elmdocci@elm-lang.jp"
            git config --global user.name "ElmDocCI"
      - run:
          name: commit changes
          command: |
            git add docs
            git commit -m 'Update docs [skip ci]'
      - run:
          name: push changes
          command: git push origin master

workflows:
  version: 2
  main:
    jobs:
      - build-and-push:
          filters:
            branches:
              only: master
